name: Headers

on:
  pull_request:

permissions: {}

jobs:
  check-headers:
    name: Check headers
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 8
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 8

      - name: Install sbt
        uses: sbt/setup-sbt@v1

      - name: Cache Coursier cache
        uses: coursier/cache-action@v6.4.0

      - name: Check headers
        run: sbt +headerCheckAll
